### ISSUE TITLE
Release a new version to rubygems

### ISSUE THREAD

**Issue by arthurnn** [peek/peek#102]
deprecations like https://github.com/peek/peek/commit/ae7c233a51e38112e7c76292e69112be9cdef9ba were fixed but not released to rubygems.org yet.
@dewski can you cut a new version?

thanks ❤️

**Comment by dewski** [comment]
Released 1.0!

https://github.com/peek/peek/releases/tag/v1.0.0

/cc @qrush @tarebyte
