### ISSUE TITLE
画像のページをリンクに差し込んでも画像が出ない問題。

### ISSUE THREAD

**Issue by keigo0331** [peek/peek#104]
画像ページをリンクに差し込もうとしても、画像がないリンクになってしまう。

http://mabo-tofu.info/wp-content/uploads/2016/06/5d2d1f1b7b936dee9fe2c0b300f07c43.jpg

![2017-06-06 13 04 12](https://cloud.githubusercontent.com/assets/18231865/26813388/af66793e-4ab8-11e7-899b-da54827e85f0.png)

**Comment by jacobbednarz** [comment]
@keigo0331 I think you might have the wrong project 😄

**Comment by keigo0331** [comment]
@jacobbednarz Sorry:bow:
