### ISSUE TITLE
System freeze

### ISSUE THREAD

**Issue by kaiwa** [peek/peek#105]
I love peek, but unfortunately it's one of the few programs with which I experience a complete system freeze. When it happens I have to hard reset my notebook.

It has happened before (sometimes) with my Thinkpad edge e540, but currently it happens **every time** I try to record a video on my Dell XPS 13 running `4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`. Tried gif and webm. The system freezes as soon as the recording countdown has finished.

Not sure how to debug it, I don't see anything useful in /var/log/syslog.

**Comment by jacobbednarz** [comment]
Hi @kaiwa,

I think you've got the wrong project :) This is for `peek` the Rails application profiling tool

**Comment by kaiwa** [comment]
Oh dammit :D thx
