### ISSUE TITLE
Peek saves metrics even when disabled

### ISSUE THREAD

**Issue by TALlama** [peek/peek#56]
When `Peek.enabled?` is `false`, the [`process_action.action_controller` callback](set_peek_request_id,) still runs and saves the data into the adapter, even though `set_peek_request_id` wasn't called (and is `nil` in my setup). In the Redis adapter, this leads to a "peek:requests:" key being created and overwritten a lot.

**Comment by salimane** [comment]
+1

**Comment by rymai** [comment]
We also experience that. At GitLab we're monkey-patching `Peek::Adapters::Redis` to not save the metrics if `Peek.request_id` is blank: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/30306/diffs

I think this could be done for all the adapters.
