### ISSUE TITLE
results is null

### ISSUE THREAD

**Issue by strika** [peek/peek#68]
For around 50% of requests in my app I get this - no results and JavaScript exception:

![screen shot 2015-03-31 at 11 00 07](https://cloud.githubusercontent.com/assets/737903/6915560/55c9ece6-d795-11e4-9c8e-808bfdbd3af8.png)

Is there something I can do to debug the issue? Is it a bug in peek? Can I give you more info about the problem?

Thanks.

**Comment by dewski** [comment]
Which [backend](https://github.com/peek/peek#configuring-the-default-adapter) are you using for storage? Any chance at seeing some development logs for the peek requests?

**Comment by strika** [comment]
I was using memory backend. I now switched to Redis and it looks like this fixes the problem. It works as expected on every request!

I didn't use different backend because this application runs on only one host. But there are multiple application server workers. If this was the problem, perhaps it can be added to the Readme.

Thanks for your help and for the amazing tool!
