### ISSUE TITLE
NameError: uninitialized constant ActiveResource::Connection::Atomic

### ISSUE THREAD

**Issue by andreorvalho** [peek/peek#89]
Hi guys,

I just updated my gems in my app and started getting this error:

bundle exec rake db:drop --trace
rake aborted!
NameError: uninitialized constant ActiveResource::Connection::Atomic
/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/peek-active_resource-1.0.0/lib/peek/views/active_resource.rb:5:in `<class:Connection>'
/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/peek-active_resource-1.0.0/lib/peek/views/active_resource.rb:1:in `<top (required)>'
/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/peek-active_resource-1.0.0/lib/peek-active_resource.rb:2:in `<top (required)>'
/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:76:in `require'
/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:72:in `each'
/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:72:in `block in require'
/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:61:in `each'
/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:61:in `require'
/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler.rb:134:in `require'
/Users/andreorvalho/projects/foodies_cube/config/application.rb:8:in `<top (required)>'
/Users/andreorvalho/projects/foodies_cube/Rakefile:4:in `require'
/Users/andreorvalho/projects/foodies_cube/Rakefile:4:in `<top (required)>'
/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-11.1.1/lib/rake/rake_module.rb:28:in `load'
/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-11.1.1/lib/rake/rake_module.rb:28:in `load_rakefile'
/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-11.1.1/lib/rake/application.rb:689:in `raw_load_rakefile'
/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-11.1.1/lib/rake/application.rb:94:in `block in load_rakefile'
/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-11.1.1/lib/rake/application.rb:176:in `standard_exception_handling'
/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-11.1.1/lib/rake/application.rb:93:in `load_rakefile'
/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-11.1.1/lib/rake/application.rb:77:in `block in run'
/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-11.1.1/lib/rake/application.rb:176:in `standard_exception_handling'
/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-11.1.1/lib/rake/application.rb:75:in `run'
/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-11.1.1/bin/rake:33:in `<top (required)>'
/opt/boxen/rbenv/versions/2.1.1/bin/rake:23:in `load'
/opt/boxen/rbenv/versions/2.1.1/bin/rake:23:in `<main>'

Is there any solution for this?

Best regards,

Andre

**Comment by jacobbednarz** [comment]
This looks to be a problem in [`peek-active_resource`](https://github.com/gotmayonase/peek-active_resource). Perhaps opening an issue there would be more appropriate?

**Comment by andreorvalho** [comment]
Allright thanks :)
