### ISSUE TITLE
Showing save dialog when rendering is started

### ISSUE THREAD

**Issue by fbruetting** [peek/peek#97]
Could you please implement showing the file choser for saving the GIF directly after recording is finished? This way rendering can run in the background and we can make the next record without having to wait for the previous rendering to finish. While showing the file choser, rendering can start in a parallel thread for further speed up. :)

**Comment by jacobbednarz** [comment]
I think you meant to open this against [phw/peek](https://github.com/phw/peek), not this one. 😛

**Comment by fb87** [comment]
Oh sorry!

**Comment by harirajv** [comment]
@fbruetting Could you please close this pull request if it is not relevant to the repo
